version: "3"

services:
  server:
    container_name: next-apollo-demo-server
    restart: always
    build: ./server
    ports:
      - "5000:5000"
  client:
    container_name: next-apollo-demo-client
    build: ./client
    environment:
      - GRAPHQL_HOST=http://localhost:5000/graphql
    ports:
      - '3000:3000'
    depends_on:
      - server